declare module "genius-lyrics-api" {
  /** Declaration file generated by dts-gen */

  export interface options {
    id?: number; // Genius song id
    title?: string = "";
    artist?: string = "";
    apiKey: string; // Genius developer access token
    optimizeQuery?: boolean; // Setting this to true will optimize the query for best results
    authHeader?: boolean; // Whether to include auth header in the search request. 'false' by default.
  }

  export interface song {
    id: number; // Genius song id
    title: string; // Song title
    artist: string; // Song artist
    url: string; // Genius webpage URL for the song
    lyrics: string; // Song lyrics
    albumArt: string; // URL of the album art image (jpg/png)
  }

  export interface searchResult {
    id: number; // Genius song id
    url: string; // Genius webpage URL for the song
    title: string; // Song title
    albumArt: string; // URL of the album art image (jpg/png)
  }
  export type url = string;

  export async function getAlbumArt(options: options): Promise<string>;

  export async function getLyrics(arg: options | url): Promise<string>;

  export async function getSong(options: options): Promise<song>;

  export async function getSongById(
    id: number | string,
    apiKey: string
  ): Promise<song>;

  export async function searchSong(options: options): Promise<searchResult>;
}
